languageCode: "en-US"
baseUrl: "https://crc.dev/blog/"
title: "CRC - Runs Containers"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

menu:
  main:
  - identifier: docs
    name: Getting Started Guide
    url: https://crc.dev/docs
    weight: 1
  - identifier: eng-docs
    name: Engineering Docs
    url: https://crc.dev/engineering-docs/
    weight: 2
  - identifier: releases
    name: Releases
    url: https://mirror.openshift.com/pub/openshift-v4/clients/crc/
    weight: 3
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 4

params:
  author: "CRC Contributors"
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  readMore: false
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  style: light
  social:
  - id: github
    name: crc-org
  - id: email
    name: devtools-cdk@redhat.com

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
